spring:
  rabbitmq:
    host: localhost
    port: 5672
  data:
    mongodb:
      database: "RANKINGS"
      host: localhost
      port: 27017
server:
  port: 8888

ranking:
  exchange: bets
  user:
    queue: points
    key: points