apiVersion: v1
kind: ConfigMap
metadata:
  name: ranking
  labels:
    app: ranking
data:
  RABBIT_HOST: "rabbitmq"
  RABBIT_PORT: 5672
  MONGO_HOST: "mongo"
  MONGO_PORT: 27017
  ENV_SPRING: "prod"
---
kind: Service
apiVersion: v1
metadata:
  name: ranking
  labels:
    app: ranking
spec:
  type: NodePort
  selector:
    app: project
  ports:
  - name: http
    port: 8888
    nodePort: 8888
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ranking
  labels:
    app: ranking
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ranking
        tier: backend
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: ranking
        image: sensedia_bet/ranking:1.0
        env:
        - name: RABBIT_HOST
          valueFrom:
            configMapKeyRef:
              name: ranking
              key: RABBIT_HOST
        - name: RABBIT_PORT
          valueFrom:
            configMapKeyRef:
              name: ranking
              key: RABBIT_PORT
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: ranking
              key: MONGO_HOST
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: ranking
              key: MONGO_PORT
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: ranking
              key: ENV_SPRING
        ports:
        - name: http
          containerPort: 8888
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1